title: Oglee
description: 벽을 눕히면 다리가 된다
author: 이현제
avatar: /logo.png
email: oglee815@gmail.com
moto : 벽을 눕히면 다리가 된다

#remote_theme: ngzhio/jekyll-theme-hamilton

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

# site :
#   skin : daylight

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
disqus: https-oglee815-github-io

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
# twitter:
#   username: ngzhio
#   card: summary
logo: logo.png
social:
  name: Hyunjae Lee
  links:
    - https://www.facebook.com/hyunjae.lee.129794/
    - https://github.com/oglee815
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en

excerpt_separator: <!--more-->
